language: node_js
node_js:
  - '9'
cache:
  directories:
    - ./node_modules
    - ./react/node_modules
stages:
  - css
  - react
jobs:
  include:
    - stage: css
      script: npm run build
      deploy:
      - provider: surge
        domain: opensanca-burro.surge.sh
        skip_cleanup: true
        project: ./dist
        on:
          tags: true
    - stage: react
      script: cd react && npm run test && npm run lint
      before_deploy:
        - npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: guilherme.albino.francisco@gmail.com
        api_key:
            secure: bqPdFuzBswBkK6EiBz8hZWqsZVleiW9p+AKolrHC/m5t0zuqHJR1icxSMOzumSBp1q+pI+J5sIkl20RmgqPtRTebvx/rjlYNEKAcO7G5y9qNSMcr1IHv5VQ9p/WI21yFPifMkH0LSpTUpPNU8W7cPu1UUdbJq4BONal2lsxUhiDDTnGH6ZCKv1d64QzYuOLSAafEzS+ZgOTZW9N5+WkekKT4hNBIHHcRZIvWbESe/9GoxBFr2Q0DpgUzLh5+cvEDYBp7+GnmrAabN6R1zZ3jaZf+PJBz3zh8e+OOXzcZVS9pO7j7Eefnozkv1EPxRyibZ5dRL2BLk9vadfuBQQB3KoGxTL4sbnAho+/pcNQxkaCCasMy+lyv/tYoTSB+xau7R3kxf9PeUd/GqbALU/P1uO+fElu2nLcrvHpLC1Rphr9/sLBb+SkCqhi4TltNoRZ2gq3FsbxCnciyeh7QCFeY78qsKHvWComG0YtLK+vo/2SGgLoMqit4YkaefEV3aF5sPS15OndRjRM35UWR3w96Lvy1wbxihsG0nvWnH+BFHoe4O4FqAynw/An38GbAT6lN8ZhckeTiKkixFmhxhnHxpa0dTpVadFYzPrZT2xmDDefy1HMjMM5iC9gUESHKbbvT/vbYAz+334AJvpPOlxSMPfdgaFzZUdn83Bh7iiPCdxc=
        on:
          tags: true
env:
  global:
    secure: KJErYfj1KX9x474Ux8p1me14FRl9ig3MlyFbvDpDyB94lVK6tp5t1Y1eZG9O0hHzLTiHY6pCQEIXTQNfjmeVQcR76yqxpP3Exm76LHR7/YlxWvWTjxbrzoffRZ2jx7cLDSf3uLnzg8IyoX7XRnHRI0oLQdnsTUEn23szjr4am5/593bvqI/iggqS4zP+3BxS+mRqCOJdi9LBgG8IIrGTT7jXHTznT/JxfoTnVaPqr4Xi9waHL+yOKMcg98fjQdzZRBw0dWGW+kfB+HlHXXPF7p+pCgdNejm1vnpCZwS8eIuD2YMBTvphdebcnpI+Lei4XmkcLH0XSgydvT9lEf5ZYQ4NW2GuV5mdd1PiwsgI5WPyHvzJ1jObRFOQieGbfMYdfQqoL4VWoFeS3dGJyMPZPD4dX0hedWqA26ZzlmHn57I5zVcDbwX7+8o5nKkMUVrYGzOEhPsgSJjhqet+K7S9RnFOMekb6dhunh88LgkjpYfI7YlHTMswkZ+DR4I22JW8NUgXUExVTwflIUNINdTWM2B1XApibMlcXsDy24EQla/g2s3EftfKlPctAemRUmskrgg6zYo7tor15wQ6wYCKX+vovgupLDtkYgIQhTw/LnM7vYmbGaZsAUTWh8paenV5pJFRD/XwWC64SQUgT2DTSLUrLqNL1bBryuT9pb29OUw=
